//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BotStatu
    {
        public int Id { get; set; }
        public string BotName { get; set; }
        public string BotStatus { get; set; }
        public string BotLink { get; set; }
    }
}
