//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyCount
    {
        public int Id { get; set; }
        public System.DateTime Day { get; set; }
        public int Groups { get; set; }
        public int Games { get; set; }
        public int Users { get; set; }
    }
}
