//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyCount
    {
        public int Id { get; set; }
        public System.DateTime Day { get; set; }
        public int Groups { get; set; }
        public int Games { get; set; }
        public int Users { get; set; }
    }
}
