//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    
    public partial class GlobalDay1Lynch_Result1
    {
        public Nullable<int> pct { get; set; }
        public string Name { get; set; }
        public int TelegramId { get; set; }
    }
}
