//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupRanking
    {
        public int GroupId { get; set; }
        public string Language { get; set; }
        public int PlayersCount { get; set; }
        public decimal MinutesPlayed { get; set; }
        public Nullable<decimal> Ranking { get; set; }
        public System.DateTime LastRefresh { get; set; }
        public int Id { get; set; }
        public int GamesPlayed { get; set; }
        public Nullable<bool> Show { get; set; }
    }
}
