//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    
    public partial class GroupDay1Lynch_Result1
    {
        public Nullable<int> pct { get; set; }
        public string Name { get; set; }
        public int TelegramId { get; set; }
    }
}
