//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Player()
        {
            this.GameKills = new HashSet<GameKill>();
            this.GameKills1 = new HashSet<GameKill>();
            this.GamePlayers = new HashSet<GamePlayer>();
            this.Groups = new HashSet<Group>();
        }
    
        public int Id { get; set; }
        public int TelegramId { get; set; }
        public string Name { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> Banned { get; set; }
        public string BannedBy { get; set; }
        public Nullable<bool> HasPM { get; set; }
        public string BanReason { get; set; }
        public string ImageFile { get; set; }
        public string Language { get; set; }
        public Nullable<int> TempBanCount { get; set; }
        public Nullable<bool> HasPM2 { get; set; }
        public Nullable<bool> HasDebugPM { get; set; }
        public Nullable<long> Achievements { get; set; }
        public string WebUserId { get; set; }
        public Nullable<int> DonationLevel { get; set; }
        public Nullable<bool> Founder { get; set; }
        public string CustomGifSet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GameKill> GameKills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GameKill> GameKills1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GamePlayer> GamePlayers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Group> Groups { get; set; }
    }
}
