//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_GroupRanking
    {
        public int GroupId { get; set; }
        public long TelegramId { get; set; }
        public string Language { get; set; }
        public string Description { get; set; }
        public string GroupLink { get; set; }
        public Nullable<decimal> Ranking { get; set; }
        public System.DateTime LastRefresh { get; set; }
        public string Name { get; set; }
    }
}
