//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_NonDefaultGroups
    {
        public string Name { get; set; }
        public string Language { get; set; }
        public Nullable<bool> ShowRoles { get; set; }
        public string ShowRolesEnd { get; set; }
        public string Mode { get; set; }
        public Nullable<int> DayTime { get; set; }
        public Nullable<int> NightTime { get; set; }
        public Nullable<int> LynchTime { get; set; }
        public Nullable<bool> AllowFool { get; set; }
        public Nullable<bool> AllowTanner { get; set; }
        public Nullable<bool> AllowCult { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> BotInGroup { get; set; }
        public Nullable<bool> DisableNotification { get; set; }
        public Nullable<int> MaxPlayers { get; set; }
        public Nullable<bool> DisableFlee { get; set; }
        public Nullable<bool> Preferred { get; set; }
        public long GroupId { get; set; }
    }
}
