//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_PreferredGroups
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public long GroupId { get; set; }
        public string Language { get; set; }
        public string UserName { get; set; }
        public string Description { get; set; }
        public string GroupLink { get; set; }
    }
}
