//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WWContext : DbContext
    {
        public WWContext()
            : base(Internal.Default.DBConnectionString)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Action> Actions { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<GameKill> GameKills { get; set; }
        public virtual DbSet<GamePlayer> GamePlayers { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<KillMethod> KillMethods { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<NotifyGame> NotifyGames { get; set; }
        public virtual DbSet<v_NonDefaultGroups> v_NonDefaultGroups { get; set; }
        public virtual DbSet<v_PreferredGroups> v_PreferredGroups { get; set; }
        public virtual DbSet<v_WaitList> v_WaitList { get; set; }
        public virtual DbSet<GlobalStat> GlobalStats { get; set; }
        public virtual DbSet<PlayerStat> PlayerStats { get; set; }
        public virtual DbSet<GroupStat> GroupStats { get; set; }
    
        public virtual ObjectResult<getPlayTime_Result> getPlayTime(Nullable<int> playerCount)
        {
            var playerCountParameter = playerCount.HasValue ?
                new ObjectParameter("playerCount", playerCount) :
                new ObjectParameter("playerCount", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getPlayTime_Result>("getPlayTime", playerCountParameter);
        }
    
        public virtual ObjectResult<getRoles_Result> getRoles(string groupName)
        {
            var groupNameParameter = groupName != null ?
                new ObjectParameter("groupName", groupName) :
                new ObjectParameter("groupName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getRoles_Result>("getRoles", groupNameParameter);
        }
    
        public virtual ObjectResult<GlobalDay1Death_Result> GlobalDay1Death()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GlobalDay1Death_Result>("GlobalDay1Death");
        }
    
        public virtual ObjectResult<GlobalDay1Lynch_Result> GlobalDay1Lynch()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GlobalDay1Lynch_Result>("GlobalDay1Lynch");
        }
    
        public virtual ObjectResult<GlobalNight1Death_Result> GlobalNight1Death()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GlobalNight1Death_Result>("GlobalNight1Death");
        }
    
        public virtual ObjectResult<GlobalSurvivor_Result> GlobalSurvivor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GlobalSurvivor_Result>("GlobalSurvivor");
        }
    
        public virtual ObjectResult<GroupDay1Death_Result> GroupDay1Death(Nullable<long> groupid)
        {
            var groupidParameter = groupid.HasValue ?
                new ObjectParameter("groupid", groupid) :
                new ObjectParameter("groupid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GroupDay1Death_Result>("GroupDay1Death", groupidParameter);
        }
    
        public virtual ObjectResult<GroupDay1Lynch_Result> GroupDay1Lynch(Nullable<long> groupid)
        {
            var groupidParameter = groupid.HasValue ?
                new ObjectParameter("groupid", groupid) :
                new ObjectParameter("groupid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GroupDay1Lynch_Result>("GroupDay1Lynch", groupidParameter);
        }
    
        public virtual ObjectResult<GroupNight1Death_Result> GroupNight1Death(Nullable<long> groupid)
        {
            var groupidParameter = groupid.HasValue ?
                new ObjectParameter("groupid", groupid) :
                new ObjectParameter("groupid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GroupNight1Death_Result>("GroupNight1Death", groupidParameter);
        }
    
        public virtual ObjectResult<GroupSurvivor_Result> GroupSurvivor(Nullable<long> groupid)
        {
            var groupidParameter = groupid.HasValue ?
                new ObjectParameter("groupid", groupid) :
                new ObjectParameter("groupid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GroupSurvivor_Result>("GroupSurvivor", groupidParameter);
        }
    }
}
